remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

exclude:
  - node_modules
  - README.md

include:
  - assets/css/custom.css

collections:
  posts:
    output: true
    permalink: /post/:path/

title: "Pubordee Khaopaisarn"